on: 
  push:
    branches:
      - master

jobs:
  release-on-push:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: release_as_stated
        if: ${{ env.TYPE == 'minor' || env.TYPE == 'major' }}
        uses: rymndhng/release-on-push-action@master
        with:
          bump_version_scheme: $TYPE
      - name: release_default
        if: ${{ failure() }}
        uses: rymndhng/release-on-push-action@master
        with:
          bump_version_scheme: patch
