on: 
  push:
    branches:
      - master

jobs:
  release-on-push:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: test vars
        run: | 
          if ${{ env.TYPE != 'minor' && env.TYPE != 'major' }}; then
            $TYPE="patch"
          fi
      - name: test previous step
        run: echo $TYPE;
      - name: release default
        uses: rymndhng/release-on-push-action@master
        with:
          bump_version_scheme: $TYPE
